# Generated by Django 4.0.1 on 2024-05-27 10:48

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crowapp', '0018_remove_editorial_created_by_delete_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('last_update_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crowapp.editor')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('hide', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='crowapp.editor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='crowapp.author')),
            ],
        ),
    ]
