# Generated by Django 4.0 on 2021-12-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crowapp.blogger')),
            ],
        ),
    ]
