# Generated by Django 4.0.1 on 2024-01-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crowapp.user',),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crowapp.user',),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crowapp.user',),
        ),
    ]
