# Generated by Django 4.0.1 on 2024-01-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0002_author_editor_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add_article', 'Can create an Article'), ('can_view_article', 'Can view an Article'), ('can_publish_article', 'Can publish an Article'), ('can_schedule_publish_article', 'Can schedule an Article to publish')]},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'permissions': [('can_add_editorial', 'Can create an Editorial'), ('can_change_editorial', 'Can modify an Editorial'), ('can_view_editorial', 'Can view an Editorial'), ('can_delete_editorial', 'Can delete an Editorial'), ('can_schedule_publish_editorial', 'Can schedule the Editorial to publish'), ('can_change_article', 'Can update an Article'), ('can_view_article', 'Can view an Article'), ('can_approve_article', 'Can approve an Article to publish'), ('can_schedule_publish_article', 'Can schedule an Article to publish'), ('can_view_author', 'Can view the author of article')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_article', 'Can read an Article')]},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
