# Generated by Django 4.0.1 on 2022-01-26 03:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0002_alter_article_content_alter_article_published_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
