# Generated by Django 4.0.1 on 2022-05-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0003_article_hide_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
