# Generated by Django 4.0.1 on 2022-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
