# Generated by Django 4.0.1 on 2024-01-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0006_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='approved_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='crowapp.editor'),
        ),
    ]
