# Generated by Django 4.0.1 on 2024-01-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0007_alter_article_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
