# Generated by Django 4.0.1 on 2024-03-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0009_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='crowapp.author'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crowapp.editor'),
        ),
    ]
