# Generated by Django 4.0.1 on 2024-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0010_alter_article_created_by_alter_editorial_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'permissions': [('can_add_editorial', 'Can create an Editorial'), ('can_change_editorial', 'Can modify an Editorial'), ('can_view_editorial', 'Can view an Editorial'), ('can_delete_editorial', 'Can delete an Editorial'), ('can_schedule_publish_editorial', 'Can schedule the Editorial to publish'), ('can_change_article', 'Can update an Article'), ('can_view_article', 'Can view an Article'), ('can_delete_article', 'Can delete an Article'), ('can_approve_article', 'Can approve an Article to publish'), ('can_schedule_publish_article', 'Can schedule an Article to publish'), ('can_view_author', 'Can view the author of article'), ('can_delete_author', 'Can delete the author')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crowapp.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'author'), ('EDITOR', 'editor'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], max_length=25),
        ),
    ]
