# Generated by Django 4.0.1 on 2024-05-19 08:02

import crowapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0011_delete_subscriber_moderator_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READER', 'reader'), ('AUTHOR', 'author'), ('EDITOR', 'editor'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], max_length=25),
        ),
    ]
