# Generated by Django 4.0.1 on 2024-05-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0012_alter_user_display_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
