# Generated by Django 4.0.1 on 2024-05-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0015_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moderator',
            options={},
        ),
    ]
