# Generated by Django 4.0.1 on 2024-05-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0016_alter_author_options_alter_editor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('can_add_editorial', 'Can create an Editorial'), ('can_change_editorial', 'Can modify an Editorial'), ('can_view_editorial', 'Can view an Editorial'), ('can_delete_editorial', 'Can delete an Editorial'), ('can_schedule_publish_editorial', 'Can schedule the Editorial to publish'), ('can_add_article', 'Can add an Article'), ('can_change_article', 'Can update an Article'), ('can_view_article', 'Can view an Article'), ('can_delete_article', 'Can delete an Article'), ('can_approve_article', 'Can approve an Article to publish'), ('can_schedule_publish_article', 'Can schedule an Article to publish'), ('can_view_author', 'Can view the author of article'), ('can_add_author', 'Can add a new Author'), ('can_change_author', 'Can modify an Author'), ('can_delete_author', 'Can delete the author')]},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add_article', 'Can create an Article'), ('can_view_article', 'Can view an Article'), ('can_publish_article', 'Can publish an Article'), ('can_schedule_publish_article', 'Can schedule an Article to publish')]},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'permissions': [('can_add_editorial', 'Can create an Editorial'), ('can_change_editorial', 'Can modify an Editorial'), ('can_view_editorial', 'Can view an Editorial'), ('can_delete_editorial', 'Can delete an Editorial'), ('can_schedule_publish_editorial', 'Can schedule the Editorial to publish'), ('can_change_article', 'Can update an Article'), ('can_view_article', 'Can view an Article'), ('can_approve_article', 'Can approve an Article to publish'), ('can_schedule_publish_article', 'Can schedule an Article to publish'), ('can_view_author', 'Can view the author of article')]},
        ),
        migrations.AlterModelOptions(
            name='moderator',
            options={'permissions': [('can_add_editorial', 'Can create an Editorial'), ('can_change_editorial', 'Can modify an Editorial'), ('can_view_editorial', 'Can view an Editorial'), ('can_delete_editorial', 'Can delete an Editorial'), ('can_schedule_publish_editorial', 'Can schedule the Editorial to publish'), ('can_change_article', 'Can update an Article'), ('can_view_article', 'Can view an Article'), ('can_delete_article', 'Can delete an Article'), ('can_approve_article', 'Can approve an Article to publish'), ('can_schedule_publish_article', 'Can schedule an Article to publish'), ('can_view_author', 'Can view the author of article'), ('can_delete_author', 'Can delete the author')]},
        ),
    ]
