# Generated by Django 4.0.1 on 2024-05-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowapp', '0017_alter_admin_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
    ]
