services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./crowcrows:/usr/src/crowcrows/
    command:
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
